module.exports = [{
        date: 'Dec 21',
        airline: 'American Airlines',
        from: 'New York (JFK)',
        to: 'London (LHR)',
        duration: 11,
        departure: '8:05 am',
        arrival: '7:00 pm',
        quantity: 10,
        price: 1313,
        img: '',
    },
    {
        date: 'Dec 22',
        airline: 'American Airlines',
        from: 'Edward L. Logam (BOS)',
        to: 'Benito Juarez (MEX)',
        duration: 15,
        departure: '7:27 pm',
        arrival: '10:25 am',
        quantity: 5,
        price: 1134,
        img: '',
    },
    {
        date: 'Dec 23',
        airline: 'Southwest Airlines',
        from: 'New York (LGA)',
        to: 'Los Angeles (LAX)',
        duration: 6,
        departure: '6:55 am',
        arrival: '12:55 pm',
        quantity: 23,
        price: 782,
        img: '',
    },
    {
        date: 'Dec 24',
        airline: 'United Airlines',
        from: 'San Francisco Int (SFO)',
        to: 'Daniel K. Inouye (HNL)',
        duration: 4,
        departure: '8:40 am',
        arrival: '12:43 pm',
        quantity: 7,
        price: 205,
        img: '',
    },
    {
        date: 'Dec 25',
        airline: 'American Airlines',
        from: 'Forthworth (DFW)',
        to: 'Newark (ERK)',
        departure: '8:40 am',
        arrival: '12:13 pm',
        quantity: 7,
        price: 205,
        img: '',
    },
    {
        date: 'Dec 26',
        airline: 'Delta Airlines',
        from: 'O\'Hare (ORD)',
        to: 'Charles de Gaulle (CDG)',
        duration: 15,
        departure: '5:20 pm',
        arrival: '8:20 am',
        quantity: 12,
        price: 419,
        img: '',
    },
    {
        date: 'Dec 27',
        airline: 'United Airlines',
        from: 'Sky Harbor (PHX)',
        to: 'Kloten (ZRH)',
        duration: 11,
        departure: '6:00 am',
        arrival: '5:10 pm',
        quantity: 27,
        price: 645,
        img: '',
    },
    {
        date: 'Dec 28',
        airline: 'American Airlines',
        from: 'Hartsfield Jackson (ATL)',
        to: 'Perth Airport (PER)',
        duration: 38,
        departure: '5:25 pm',
        arrival: '8:35 pm',
        quantity: 19,
        price: 2188,
        img: '',
    },
    {
        date: 'Dec 29',
        airline: 'United Airlines',
        from: 'Newark (EWR)',
        to: 'OR Tambo (JNB)',
        duration: 35,
        departure: '5:10 pm',
        arrival: '11:10 pm',
        quantity: 28,
        price: 715,
        img: '',
    },
    {
        date: 'Dec 30',
        airline: 'United Airlines',
        from: 'Orlando Int Airport (MCO)',
        to: 'Incheon (ICN)',
        duration: 38,
        departure: '4:10 pm',
        arrival: '6:20 pm',
        quantity: 4,
        price: 873,
        img: '',
    },
];