module.exports = [{
        flight_date: 'Dec 21',
        airline_name: 'American Airline',
        from_location: 'New York (JFK)',
        to_location: 'London (LHR)',
        departure_time: '8:05 am',
        arrival_time: '6:50 pm',
        quantity: 10,
        price: 1313,
        img: '',
        round_trip: true,
    },
    {
        flight_date: 'Dec 22',
        airline_name: 'DBA United Express',
        from_location: 'Boston (BOS)',
        to_location: 'Mexico (MEX)',
        departure_time: '7:27 pm',
        arrival_time: '10:00 am',
        quantity: 5,
        price: 1134,
        img: '',
        round_trip: true,
    },
    {
        flight_date: 'Dec 23',
        airline_name: 'DBA United Express',
        from_location: 'Boston (BOS)',
        to_location: 'Mexico (MEX)',
        departure_time: '7:27 pm',
        arrival_time: '10:00 am',
        quantity: 5,
        price: 1134,
        img: '',
    },
]